### ISSUE TITLE
I'm facing error when i have to deploy graphql in studio folder using this commnd : sanity graphql deploy

### ISSUE THREAD

**Issue by mohil-8twelve-mortgage** [ShaifArfan/techHub-blog#15]
✔ Checking for deployed API
? Do you want to enable a GraphQL playground? Yes
✔ Generating GraphQL schema
✖ Validating GraphQL API

ReferenceError: URL is not defined
    at handler (C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/@sanity/cli/node_modules/get-it/src/middleware/defaultOptionsProcessor.ts:13:15)
    at applyMiddleware (C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/@sanity/cli/node_modules/get-it/src/util/middlewareReducer.ts:8:15)
    at requester (C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/@sanity/cli/node_modules/get-it/src/createRequester.ts:44:21)
    at httpRequest (C:/Users/INILPTP044/AppData/Roaming
![Screenshot 2023-03-30 204908](https://user-images.githubusercontent.com/128118167/228884350-1e6f3c6f-f7c0-4751-abc0-91675b13c7b1.png)
/npm/node_modules/@sanity/client/dist/index.js:107:12)    at Observable._subscribe (C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/@sanity/client/dist/index.js:821:3)  
    at Observable._trySubscribe (C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/rxjs/dist/esm5/internal/Observable.js:38:25)
    at cb (C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/rxjs/dist/esm5/internal/Observable.js:32:31)    at errorContext (C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/rxjs/dist/esm5/internal/util/errorContext.js:19:9)
    at Observable.subscribe (C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/rxjs/dist/esm5/internal/Observable.js:23:9)
    at C:/Users/INILPTP044/AppData/Roaming/npm/node_modules/rxjs/dist/esm5/internal/operators/filter.js:6:16
![Screenshot 2023-03-30 204908](https://user-images.githubusercontent.com/128118167/228884451-b3ff12bf-6e83-4506-8924-92f89556189c.png)

**Comment by PhantomLord666** [comment]
Is the version of cli, you have to use v2
